// <auto-generated />
using System;
using CodingTest.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodingTest.DAL.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodingTest.BAL.Domain.CandiateTracker", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CandiateExpertise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandiateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContactedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterviewedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JoiningOrderSenton")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecruiterEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcingDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stratergy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.HasIndex("RecruiterEmployeeId");

                    b.ToTable("CandiateTracker");
                });

            modelBuilder.Entity("CodingTest.BAL.Domain.Recruiter", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BusinessUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Recruiter");
                });

            modelBuilder.Entity("CodingTest.BAL.Domain.SourcingDefinition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CloseBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenFrom")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpenPositions")
                        .HasColumnType("int");

                    b.Property<string>("SearchCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcingStratergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetCompanies")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SourcingDefinition");
                });

            modelBuilder.Entity("CodingTest.BAL.Domain.CandiateTracker", b =>
                {
                    b.HasOne("CodingTest.BAL.Domain.Recruiter", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterEmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
